### ISSUE TITLE
Fixes

### ISSUE THREAD

**Issue by lucycull** [machooper/start-serpent#1]
# Issues 

Version: 1

## MacBook

- [x] Footer: email address box is further to the right than the name input
- [x] Adapt isn't a link
- [ ] About: when you click 'contact' it loads halfway down the page
- [x] Artists: latest releases and the album artwork aren't centred to each other
- [ ] Contact nav link sends me to a 404 page

## 4K Monitor

- [x] Artists: the image and the text aren't centred horizontally to each other

## iPhone

- [ ] Buggy scroll (it doesn't scroll all the way down to the adapt text in the footer)
- [x] Artists: text and listen now button should be centred 
- [ ] After clicking on the contact link in the nav it says 404 and every link clicked on after that says 404 too

## iPad 

- [x] Artists: the image is too big and the text goes off the page

**Comment by macrestored** [comment]
# Issues

version: 2

## MacBook
- [x] About: when you click 'contact' it loads halfway down the page
- [ ] Contact nav link sends me to a 404 page

## iPhone
- [x]  Buggy scroll (it doesn't scroll all the way down to the adapt text in the footer)
- [ ] After clicking on the contact link in the nav it says 404 and every link clicked on after that says 404 too

**Comment by macrestored** [comment]
# Issues

version: 3

## General
- [x] Nav links on dynamic pages return 404
